backend/moyu/moyu/urls.py
# -*- coding: utf-8 -*-  
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('moyuweb/',include('moyuweb.urls')),
]

backend/moyu/moyuweb/urls.py
from django.urls import path

from . import views

app_name = "moyuweb"

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name="login"),
    path('login_auth', views.login_auth, name="login_auth"),
    path('logout/', views.logout, name="logout"),
    path('issue/', views.issue, name="issue"),
    path('me_sale/', views.me_sale, name="me_sale"),
    path('me_transaction/', views.me_transaction, name="me_transaction"),
]

backend/moyu/moyuweb/models.py
# -*- coding: utf-8 -*-  
from django.db import models
from django.contrib.auth.hashers import make_password, check_password
# Create your models here.

class Follower(models.Model):
    Follower=models.BigIntegerField()
    Following=models.BigIntegerField()

class User(models.Model):        
        
    UserId=models.AutoField(primary_key=True)
    UserType=models.IntegerField(default=1)
    Nickname=models.CharField(max_length=50)
    Icon=models.ImageField()
    Photo=models.ImageField()
    Email=models.CharField(max_length=50)
    PhoneNumber=models.IntegerField(default=0)
    Password=models.CharField(max_length=254)
    isIdentified=models.BooleanField(default=False)
    isVIP=models.BooleanField(default=False)
    CreatedAt=models.DateTimeField(auto_now_add=True)
    UpdateAt=models.DateTimeField(auto_now=True)

    def Create_User(self,Email,Password,Nickname="John Doe"):
        UserType=1

        psw=make_password(Password)
        new_user=User(UserType=UserType,Nickname=Nickname,Email=Email,Password=psw)

        user_list=User.objects.filter(Email=Email)
        if(len(user_list)!=0):  return "Email same"
        else:   
            new_user.save()
            return new_user.UserId

    def Login(self,Email,Password):
        user_list=User.objects.filter(Email=Email)
        if(len(user_list)!=1):  return "user does not exist"
        if(check_password(Password,user_list[0].Password)): return True
        else:   return "wrong password"

    def __str__(self):
        return self.UserId+self.UserType+self.Nickname

class AppendInfos(models.Model):
    #UserId=models.ForeignKey(User,on_delete=models.CASCADE)
    UserId=models.AutoField(primary_key=True)
    MoyuCoin=models.IntegerField(default=0)

class Buyer(models.Model):
    #UserId=models.ForeignKey(User,on_delete=models.CASCADE)
    UserId=models.AutoField(primary_key=True)
    DeliveryState=models.CharField(max_length=50)

class Seller(models.Model):
    #UserId=models.ForeignKey(User,on_delete=models.CASCADE)
    UserId=models.AutoField(primary_key=True)
    Credit=models.CharField(max_length=50)
    Star=models.IntegerField(default=0)

class Item(models.Model):
    ItemId=models.AutoField(primary_key=True)
    #UserId=models.ForeignKey(User,on_delete=models.CASCADE)
    UserId=models.BigIntegerField()
    Name=models.CharField(max_length=50)
    Price=models.CharField(max_length=50)
    Description=models.TextField(max_length=65535)
    isForRent=models.BooleanField(default=False)
    ShortCut=models.CharField(max_length=50)
    Datetime=models.DateTimeField(auto_now_add=True)
    Place=models.CharField(max_length=50)
    BaoYou=models.BooleanField(default=False)
    Negotiation=models.BooleanField(default=False)
    Classification=models.CharField(max_length=50)
    AppendInfoId=models.CharField(max_length=50)
    VisitNum=models.IntegerField(default=0)
    XinJiu=models.CharField(max_length=50)

    def Create_Item(self,UserId,Name):
        user_list=User.objects.filter(UserId=UserId)
        if(len(user_list)!=1):   return "cannot find user"
        new_item=Item(UserId=UserId,Name=Name)
        new_item.save()
        return new_item.ItemId

class Order(models.Model):
    OrderId=models.AutoField(primary_key=True)
    BuyerId=models.BigIntegerField()
    SellerId=models.BigIntegerField()
    #ItemId=models.ForeignKey(Item,on_delete=models.CASCADE,)
    ItemId=models.BigIntegerField()
    CreatedAt=models.DateTimeField(auto_now_add=True)
    Address=models.CharField(max_length=254,default='')
    DeliveryState=models.CharField(max_length=50)

    def Create_Order(self,BuyerId,SellerId,ItemId,Address,DeliveryState="未发货"):
        buyer_list=User.objects.filter(UserId=BuyerId)
        if(len(buyer_list)!=1):   return "cannot find buyer"
        seller_list=User.objects.filter(UserId=SellerId)
        if(len(seller_list)!=1):   return "cannot find seller"
        item_list=Item.objects.filter(ItemId=ItemId)
        if(len(item_list)!=1):   return "cannot find item"

        new_order=Order(BuyerId=BuyerId,SellerId=SellerId,ItemId=ItemId,Address=Address,DeliveryState=DeliveryState)
        new_order.save()
        return new_order.OrderId


class Comment(models.Model):
    CommentId=models.AutoField(primary_key=True)
    #ItemId=models.ForeignKey(Item,on_delete=models.CASCADE,)
    ItemId=models.BigIntegerField()
    #UserId=models.ForeignKey(User,on_delete=models.CASCADE,)
    UserId=models.BigIntegerField()
    Text=models.TextField(max_length=65535)
    Datetime=models.DateTimeField(auto_now_add=True)
    SubCommentId=models.BigIntegerField(default=None)

    def Create_Comment(self,ItemId,UserId,Text="",SubCommentId=-1):
        user_list=User.objects.filter(UserId=UserId)
        if(len(user_list)!=1):   return "cannot find user"
        item_list=Item.objects.filter(ItemId=ItemId)
        if(len(item_list)!=1):   return "cannot find item"
        if(SubCommentId!=-1):
            Comment_list=Comment.objects.filter(CommentId=SubCommentId)
            if(len(Comment_list)!=1):   return "cannot find comment"
        new_comment=Comment(ItemId=ItemId,UserId=UserId,Text=Text,SubCommentId=SubCommentId)
        new_comment.save()
        return new_comment.CommentId

    def __str__(self):
        return "Item:"+self.ItemId+":"+"User:"+self.UserId+":"+self.Datetime

class Reward(models.Model):
    RewardId=models.AutoField(primary_key=True)
    #UserId=models.ForeignKey(Buyer,on_delete=models.CASCADE,)
    UserId=models.BigIntegerField()
    Name=models.CharField(max_length=50)
    Description=models.TextField(max_length=65535)
    Price=models.IntegerField(default=0)
    #Negotiation=models.BooleanField
    CreatedAt=models.DateTimeField(auto_now_add=True)
    Place=models.CharField(max_length=50)

    def Create_Reward(self,UserId,Name="default_name",Description="",Price=0,Place=""):
        user_list=User.objects.filter(UserId=UserId)
        if(len(user_list)!=1):   return "cannot find user"
        new_reward=Reward(UserId=UserId,Name=Name,Description=Description,Price=Price,Place=Place)
        new_reward.save()
        return new_reward.RewardId

backend/moyu/moyuweb/views.py
from django.shortcuts import render, redirect
from .models import User
import datetime


# Create your views here.

def index(request):
    email = request.COOKIES.get("Email")
    if not email:
        return render(request, "moyuweb/index.html", {})
    user = User.objects.get(Email=email)
    print(user.Nickname)
    return render(request, "moyuweb/index.html", {"Nickname": user.Nickname})


def login(request):
    context = {}
    context["title"] = "login"
    return render(request, "moyuweb/login.html", context)


def login_auth(request):
    context = {}
    if request.POST:
        email = request.POST['email']
        password = request.POST['password']
        r_msg = User.Login(User, email, password)
        if r_msg == True:
            context = {
                "success_msg": "you succeed in login"
            }
            res = redirect("/moyuweb")
            current_time = datetime.datetime.utcnow()
            current_data = current_time + datetime.timedelta(seconds=60 * 60 * 24 * 7)
            # u = User.objects.get(Email=email)
            # res.set_cookie("Nickname",u.Nickname)
            res.set_cookie("Email", email, expires=current_data)
            return res
        else:
            context = {
                "error_msg": "email or password is wrong"
            }
    else:
        context = {
            "error_msg": "post no message"
        }
    return render(request, "moyuweb/login.html", context)


def logout(request):
    res = redirect("/moyuweb")
    res.delete_cookie("Email")
    return res


def issue(request):
    context = {}
    context["title"] = "issue"
    return render(request, "moyuweb/issue.html", context)


def me_sale(request):
    context = {}
    context["title"] = "me_sale"
    return render(request, "moyuweb/me_sale.html", context)


def me_transaction(request):
    context = {}
    context["title"] = "me_transaction"
    return render(request, "moyuweb/me_transaction.html", context)

backend/moyu/moyuweb/templates/moyuweb/base.html
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>MOYU!</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" crossorigin="anonymous" />
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #ffda44;">
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;
        <img src="https://img.alicdn.com/tps/i3/TB1ys1sHVXXXXcrXVXXL_ZfHFXX-208-46.png">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/moyuweb">首页&nbsp;&nbsp;&nbsp;<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="#">二手&nbsp;&nbsp;&nbsp;</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="#">估价&nbsp;&nbsp;&nbsp;</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="#">降降降&nbsp;&nbsp;&nbsp;</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="#">|&nbsp;&nbsp;&nbsp;</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/moyuweb/issue">发布闲置&nbsp;&nbsp;&nbsp;</a>
                </li>
                <li class="nav-item dropdown active">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                        我的闲置
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="/moyuweb/me_sale">出售中</a>
                        <a class="dropdown-item" href="/moyuweb/me_transaction">交易中</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="logout">登出</a>
                    </div>
                </li>
                <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                </li>
                <li>
                    <form class="form-inline my-2 my-lg-0">
                        <input class="form-control mr-sm-2" type="search" placeholder="🐟" aria-label="Search">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
                    </form>
                </li>
            </ul>

        </div>
    </nav>
    {% block body %}{% endblock %}
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
    crossorigin="anonymous"></script>

</html>

backend/moyu/moyuweb/templates/moyuweb/index.html
{% extends "moyuweb/base.html" %}

{% block body %}
    <br/>
    <br/>
    <div class="row">
        <div class="col-1"></div>
        <div class="col-2">
            <div class="list-group" id="list-tab" role="tablist">
                <a class="list-group-item " data-toggle="list">闲置数码</a>
                <a class="list-group-item " data-toggle="list">闲置母婴</a>
                <a class="list-group-item " data-toggle="list">家庭日用</a>
                <a class="list-group-item" data-toggle="list">影音家电</a>
            </div>
        </div>
        <div class="col-4">
            <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img class="img-fluid" src="http://img.alicdn.com/tps/TB1Ntl6NpXXXXaIXpXXXXXXXXXX-640-270.jpg"
                             alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="img-fluid" src="http://img.alicdn.com/tps/TB1Ntl6NpXXXXaIXpXXXXXXXXXX-640-270.jpg"
                             alt="Second slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
        <div class="col-4">
            <div class="container">
                <div class="row">
                    <div class="col">
                        <div class="card">
                            <div class="card-body">
                                <h2 class="card-title">发布闲置</h2>
                                <br>
                                <p class="card-text">闲置换钱 快速出手</p>
                                <br>
                                <a href="#" class="btn btn-primary">现在就去发布</a>
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="card">
                            <div class="card-body">
                                <h2 class="card-title">一键转卖</h2>
                                <br>
                                <p class="card-text">转卖已买到的宝贝</p>
                                <br>
                                <a href="#" class="btn btn-primary">现在就去转卖</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-1"></div>
        <div class="col-2"><br><br>
            <div class="card">
                <div class="card-body">
                    {% if Nickname %}
                        <h5 class="card-title">
                            Hi, {{ Nickname }}🐟你可能感兴趣</h5>
                        <br>
                    {% else %}
                        <h5 class="card-title">
                            Hi,先<a href="login">登录吧</a><br>这里有更多你感兴趣的
                        </h5>
                    {% endif %}
                    <p class="card-text"><a href="">摩托</a> <a href="">平板</a> <a href="">算法导论</a><br><br><a
                            href="">小说</a>
                        <a href="">电视</a></p>
                    <br><br>
                </div>
            </div>
        </div>
        <div class="col-5">

            <ul class="nav nav-tabs" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" href="#profile" role="tab" data-toggle="tab">猜你喜欢</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#buzz" role="tab" data-toggle="tab">全新闲置</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#references" role="tab" data-toggle="tab">同城交易</a>
                </li>
            </ul>

            <!-- Tab panes -->
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane fade in active" id="profile">
                    <div class="row text-center">
                        <div class="col">
                            <figure>
                                <img src="https://img.alicdn.com/bao/uploaded/i4/6000000006433/TB2BKDaX4GYBuNjy0FnXXX5lpXa_!!0-fleamarket.jpg_160x160.jpg"
                                     alt="">
                                <figcaption>9成新乐和电动折叠车</figcaption>
                            </figure>
                        </div>
                        <div class="col">
                            <figure>
                                <img src="https://img.alicdn.com/bao/uploaded/i1/6000000002475/TB2KGE7itbJ8KJjy1zjXXaqapXa_!!0-fleamarket.jpg_160x160.jpg"
                                     alt="">
                                <figcaption>冰裂茶具</figcaption>
                            </figure>
                        </div>
                        <div class="col">
                            <figure>
                                <img src="https://img.alicdn.com/bao/uploaded/i4/6000000003486/TB2YRWga6nD8KJjSspbXXbbEXXa_!!0-fleamarket.jpg_160x160.jpg"
                                     alt="">
                                <figcaption>书架 书柜 家具 高1.8m 宽</figcaption>
                            </figure>
                        </div>
                    </div>
                </div>
                <div role="tabpanel" class="tab-pane fade" id="buzz">待上架</div>
                <div role="tabpanel" class="tab-pane fade" id="references">待上架</div>
            </div>


        </div>
        <div class="col-3">
            <br>
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">好友正在出售</h5>
                </div>
                <div class="card-text">

                    <figure>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img
                            src="https://img.alicdn.com/bao/uploaded/i4/6000000006433/TB2BKDaX4GYBuNjy0FnXXX5lpXa_!!0-fleamarket.jpg_160x160.jpg"
                            alt="">
                        <figcaption>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 9成新乐和电动折叠车</figcaption>
                    </figure>
                </div>
            </div>

        </div>
    </div>

    <div class="text">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;所有的宝贝都在这里
    </div>
    <hr>
    <div class="row">

    </div>

{% endblock %}

backend/moyu/moyuweb/templates/moyuweb/issue.html
{% extends "moyuweb/base.html" %}

{% block body %}
    <br/>
    <br/>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2">
            </div>
            <div class="col-md-5">
                <h4>
                    今天您有什么闲置宝贝想要出售？
                </h4>
            </div>
            <div class="col-md-5">
            </div>
        </div>
        <br/>
        <div class="row">
            <div class="col-md-2">
            </div>
            <div class="col-md-5">
                <form style="width:500px">
                    <div class="form-group">
                        <label for="title">
                            <strong>
                                标题：
                            </strong>
                        </label>
                        <input class="form-control" id="title" placeholder="给宝贝起个名字吧～" type="text">
                        </input>
                    </div>
                    <div class="form-group">
                        <label for="class">
                            <strong>
                                类别：
                            </strong>
                        </label>
                        <select class="form-control" id="class" style="width:200px">
                            <option value="c1">
                                数码产品
                            </option>
                            <option value="c2">
                                母婴用品
                            </option>
                            <option value="c3">
                                家居日用
                            </option>
                            <option value="c4">
                                影音家电
                            </option>
                            <option value="c5">
                                鞋服配饰
                            </option>
                            <option value="c6">
                                珠宝收藏
                            </option>
                            <option value="c7">
                                其他
                            </option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="isnew">
                            <strong>
                                新旧：
                            </strong>
                        </label>
                        <div>
                            <label class="radio-inline">
                                <input name="radio" type="radio">
                                全新
                                </input>
                            </label>
                            <label class="radio-inline">
                                <input name="radio" type="radio">
                                非全新
                                </input>
                            </label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="price">
                            <strong>
                                售价：
                            </strong>
                        </label>
                        <input class="form-control" id="price" placeholder="元" type="text">
                        </input>
                    </div>
                    <div class="form-group">
                        <label for="bargin">
                            <strong>
                                讲价：
                            </strong>
                        </label>
                        <div>
                            <label class="radio-inline">
                                <input name="radio" type="radio">
                                接受
                                </input>
                            </label>
                            <label class="radio-inline">
                                <input name="radio" type="radio">
                                拒绝
                                </input>
                            </label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="post">
                            <strong>
                                运费：
                            </strong>
                        </label>
                        <input class="form-control" id="post" placeholder="元" type="text">
                        </input>
                    </div>
                    <div class="form-group">
                        <label for="phone">
                            <strong>
                                联系方式：
                            </strong>
                        </label>
                        <input class="form-control" id="phone" placeholder="手机号" type="text">
                        </input>
                    </div>
                    <div class="form-group">
                        <label for="inputFile">
                            <strong>
                                宝贝图片：
                            </strong>
                        </label>
                        <input class="form-control-file" id="inputFile" type="file"/>
                        <p class="help-block" style="color: #b0b0b0;">
                            最多可上传十张照片
                        </p>
                    </div>
                    <div class="form-group">
                        <label for="description">
                            <strong>
                                宝贝描述：
                            </strong>
                        </label>
                        <textarea class="form-control" id="description" placeholder="请介绍一下您的宝贝吧～" rows="8">
                            </textarea>
                    </div>
                    <button class="btn btn-primary" style="background-color: #ffda44;" type="submit">
                        立即发布
                    </button>
                    <div>
                    </div>
                    <div>
                    </div>
                </form>
            </div>
            <div class="col-md-5">
                <!--img alt="Bootstrap Image Preview" src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1539006779365&di=06dfcb071c2c7ceaf521e48e33fbe406&imgtype=0&src=http%3A%2F%2Fwww.kviso.com%2Fsoft%2FUploadPic%2F2014-11%2F2014112316154616672.jpg" /-->
                <img alt="Bootstrap Image Preview"
                     src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1539014327768&di=3ba6101ee0957b3818ab21ef04ad218f&imgtype=0&src=http%3A%2F%2Fe.hiphotos.baidu.com%2Fzhidao%2Fpic%2Fitem%2F80cb39dbb6fd526664a714ada018972bd50736fe.jpg"/>
            </div>
        </div>
    </div>
    <br/>
    <br/>
{% endblock %}

backend/moyu/moyuweb/templates/moyuweb/layout.html
{% load static %}
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <link href="{% static "node_modules/bootstrap/dist/css/bootstrap.css" %}" rel="stylesheet">
    <link href="{% static "node_modules/bootstrap-vue/dist/bootstrap-vue.css" %}" rel="stylesheet">
    {% block custom_stylesheets %}{% endblock %}
  </head>

  {% block body %}{% endblock %}

  <script src="{% static "node_modules/vue/dist/vue.js" %}"></script>
  <script src="{% static "node_modules/babel-polyfill/dist/polyfill.js" %}"></script>
  <script src="{% static "node_modules/bootstrap-vue/dist/bootstrap-vue.js" %}"></script>
  {% block custom_javascripts %}{% endblock %}
</html>

backend/moyu/moyuweb/templates/moyuweb/login.html
{% extends "moyuweb/layout.html" %}
{% load static %}

{% block custom_stylesheets %}
<link href="{% static "stylesheets/login.css" %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block body %}
<body>
  <div class="logo">
    <img src="{% static "imgs/logo.png" %}">
  </div>
  <div class="bg"></div>
  <div class="login-container">
    <form class="form-signin" action="{% url "moyuweb:login_auth" %}" method="POST">
      {% csrf_token %}
      <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
      <label for="inputEmail" class="sr-only">Email address</label>
      <input name="email" type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
      <label for="inputPassword" class="sr-only">Password</label>
      <input name="password" type="password" id="inputPassword" class="form-control" placeholder="Password" required>
      <div class="checkbox mb-3">
        <label>
          <input type="checkbox" value="remember-me"> Remember me
        </label>
      </div>
      <div>
          {% if error_msg %}<p><strong>{{ error_msg }}</strong></p>{% endif %}
      </div>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      <div class="register"><a href="/register">Register for Free!</a></div>
    </form>
  </div>
</body>
{% endblock %}